baseurl: "/" # Controls base URL
languageCode: "en-US" # Controls html lang attribute
title: "NeuronStar" # Homepage title and page title suffix
paginate: 12 # Number of posts to show before paginating
theme: "bulma" # to use as default theme

enableRobotsTXT: true # Suggested, it generates a robots.txt
googleAnalytics: "UA-61051776-1" # Optional, add tracking Id for analytics
disqusShortname: "" # Optional, add Disqus shortname for comments
SectionPagesMenu: "main" # Enable menu system for lazy bloggers


menu:
  main:
    - name: ESL
      weight: 1
      identifier: esl
      url: /esl/
    - name: SNM
      weight: 3
      identifier: snm
      url: /snm/

params:
  theme_variant: "flatly" # possible value for the theme_variant `cerulean,cosmo,cyborg,darkly,flatly,journal,litera,lumen,lux,materia,minty,pulse,sandstone,simplex,slate,solar,spacelab,superhero,united,yeti`
  description: "We explore neuroscience, machine learning, complex system and intelligence"
  powered_by: "love" # Optional, controls name display on footer
  hide_author: false # Optional, set true to hide author name on posts
  images: # Suggested, controls default OpenGraph images controls author name display on meta tag
  github: "neuronstar" # Optional, to display link to github account in menu bar
  twitter: "" # Optional, to display link to twitter account in menu bar
  author: "NeuronStar"
  editURL: "https://github.com/neurnstar/neuronstar.github.io/edit/master/content/"
  algolia:
    vars:
      - "title"
      - "summary"
      - "date"
      - "publishdate"
      - "expirydate"
      - "permalink"
      - "images"
      - "author"
      - "fields"
      - "platforms"
      - "file"
    params:
      - "categories"
      - "tags"
    options:
      appId: "NQED3STBQT"
      apiKey: "5b7ac3f0c287018586467528f312e255"
      indexName: "kausalflow-research-tools"
      hitsPerPage: 12
      routing: true



outputFormats:
  Algolia:
    baseName: "algolia"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true

outputs:
  home:
    - "HTML"
    - "RSS"
    - "Algolia"
